title: Tien Nguyen
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://nguditi.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  github: nguditi
  email: tienandehit@gmail.com

disqus:
    shortname: tiennd
